# Generated by Django 4.0.5 on 2022-07-15 17:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('text1', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
