# Generated by Django 4.0.5 on 2022-07-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wiki',
            new_name='Post',
        ),
    ]
