# Generated by Django 3.2.11 on 2022-07-02 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20220702_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tracker.article'),
        ),
    ]
