# Generated by Django 3.2.11 on 2022-07-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20220702_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='tracker.article'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
