# Generated by Django 4.0.5 on 2022-07-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_article_subtitle2_article_subtitle3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='articles',
        ),
        migrations.AddField(
            model_name='product',
            name='articles',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='tracker.article'),
        ),
    ]
