# Generated by Django 4.0.5 on 2022-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_article_text11_article_text12_article_text13_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('servingSize', models.CharField(max_length=300)),
                ('Fat', models.FloatField()),
                ('Protein', models.FloatField()),
                ('Carbohydrates', models.FloatField()),
                ('Fiber', models.FloatField()),
                ('netCarbohydrates', models.FloatField()),
                ('text', models.TextField(max_length=2000)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
