# Generated by Django 3.2.11 on 2022-07-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20220711_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='percenttProtein',
            new_name='percentProtein',
        ),
    ]
